apiVersion: v1
kind: Service
metadata:
  name: order-web
  namespace: hanbat-syoushty
  labels:
    app: order-web
spec:
  selector:
    app: order-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
